version: '3.7'

services:
  angular-service:
    container_name: angular-container
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - '4200:4200'
    command:
      bash -c "yarn && ng serve --host 0.0.0.0 --port 4200"
